// Auto-generated by .github/workflows/update-fx-rates.yml — do not edit by hand.
// Source: European Commission, InforEuro monthly accounting rates (1 EUR = value units).
const FX_RATES = {
  "source": "European Commission — InforEuro monthly accounting rates",
  "url": "https://commission.europa.eu/funding-and-tenders/procedures-guidelines-tenders/information-contractors-and-beneficiaries/exchange-rate-inforeuro_en",
  "year": 2026,
  "month": 10,
  "fetchedAt": "2026-10-03T11:26:19Z",
  "rates": {
    "EUR": {
      "value": 1,
      "currency": "Euro",
      "country": "Belgium"
    },
    "CZK": {
      "value": 24.411,
      "currency": "Czech koruna",
      "country": "Czechia"
    },
    "DKK": {
      "value": 7.4754,
      "currency": "Danish krone",
      "country": "Denmark"
    },
    "HUF": {
      "value": 366.38,
      "currency": "Hungarian forint",
      "country": "Hungary"
    },
    "PLN": {
      "value": 4.3653,
      "currency": "Polish zloty",
      "country": "Poland"
    },
    "RON": {
      "value": 5.2786,
      "currency": "Romanian Leu",
      "country": "Romania"
    },
    "SEK": {
      "value": 11.321,
      "currency": "Swedish krona",
      "country": "Sweden"
    },
    "AUD": {
      "value": 1.6211,
      "currency": "Australian dollar",
      "country": "Australia"
    },
    "BRL": {
      "value": 5.9177,
      "currency": "Brazilian real",
      "country": "Brazil"
    },
    "CAD": {
      "value": 1.6101,
      "currency": "Canadian dollar",
      "country": "Canada"
    },
    "CNY": {
      "value": 7.6117,
      "currency": "Chinese Yuan Renminbi",
      "country": "China"
    },
    "HKD": {
      "value": 8.9091,
      "currency": "Hong Kong dollar",
      "country": "Hong Kong"
    },
    "ISK": {
      "value": 136.8,
      "currency": "Iceland króna",
      "country": "Iceland"
    },
    "INR": {
      "value": 108.991,
      "currency": "Indian rupee",
      "country": "India"
    },
    "IDR": {
      "value": 20350.09,
      "currency": "Indonesian rupiah",
      "country": "Indonesia"
    },
    "ILS": {
      "value": 3.4702,
      "currency": "New Israeli shekel",
      "country": "Israel"
    },
    "JPY": {
      "value": 178.41,
      "currency": "Japanese yen",
      "country": "Japan"
    },
    "MYR": {
      "value": 4.634,
      "currency": "Malaysian ringgit",
      "country": "Malaysia"
    },
    "MXN": {
      "value": 20.3222,
      "currency": "Mexican peso",
      "country": "Mexico"
    },
    "NZD": {
      "value": 2.0076,
      "currency": "New Zealand dollar",
      "country": "New Zealand"
    },
    "NOK": {
      "value": 10.8735,
      "currency": "Norwegian krone",
      "country": "Norway"
    },
    "PHP": {
      "value": 71.022,
      "currency": "Philippine piso",
      "country": "Philippines"
    },
    "RUB": {
      "value": 96.2499,
      "currency": "Russian ruble",
      "country": "Russia"
    },
    "SGD": {
      "value": 1.4504,
      "currency": "Singapore dollar",
      "country": "Singapore"
    },
    "ZAR": {
      "value": 18.5887,
      "currency": "South African rand",
      "country": "South Africa"
    },
    "KRW": {
      "value": 1536.74,
      "currency": "South Korean won",
      "country": "South Korea"
    },
    "CHF": {
      "value": 0.9461,
      "currency": "Swiss franc",
      "country": "Switzerland"
    },
    "THB": {
      "value": 38.056,
      "currency": "Thai baht",
      "country": "Thailand"
    },
    "TRY": {
      "value": 55.6398,
      "currency": "Turkish lira",
      "country": "Turkey"
    },
    "GBP": {
      "value": 0.85718,
      "currency": "Pound sterling",
      "country": "United Kingdom"
    },
    "USD": {
      "value": 1.1355,
      "currency": "United States dollar",
      "country": "United States"
    },
    "AFN": {
      "value": 74,
      "currency": "Afghan afghani",
      "country": "Afghanistan"
    },
    "ALL": {
      "value": 92.045,
      "currency": "Albanian lek",
      "country": "Albania"
    },
    "DZD": {
      "value": 152.1975,
      "currency": "Algerian dinar",
      "country": "Algeria"
    },
    "AOA": {
      "value": 1045.79,
      "currency": "Angolan kwanza",
      "country": "Angola"
    },
    "ARS": {
      "value": 1731.6375,
      "currency": "Argentine peso",
      "country": "Argentina"
    },
    "AMD": {
      "value": 413.5,
      "currency": "Armenian dram",
      "country": "Armenia"
    },
    "AWG": {
      "value": 2.05526,
      "currency": "Aruban florin",
      "country": "Aruba"
    },
    "AZN": {
      "value": 1.93035,
      "currency": "Azerbaijan Manat",
      "country": "Azerbaijan"
    },
    "BSD": {
      "value": 1.1355,
      "currency": "Bahamian dollar",
      "country": "Bahamas (the)"
    },
    "BHD": {
      "value": 0.42806,
      "currency": "Bahraini dinar",
      "country": "Bahrain"
    },
    "BDT": {
      "value": 139.80844,
      "currency": "Bangladeshi taka",
      "country": "Bangladesh"
    },
    "BBD": {
      "value": 2.28701,
      "currency": "Barbados dollar",
      "country": "Barbados"
    },
    "BYN": {
      "value": 3.4404,
      "currency": "Belarussian rouble",
      "country": "Belarus"
    },
    "BZD": {
      "value": 2.28372,
      "currency": "Belize dollar",
      "country": "Belize"
    },
    "BMD": {
      "value": 1.1355,
      "currency": "Bermudian dollar",
      "country": "Bermuda"
    },
    "BTN": {
      "value": 108.991,
      "currency": "Bhutanese ngultrum",
      "country": "Bhutan"
    },
    "BOB": {
      "value": 13.68845,
      "currency": "Bolivian boliviano",
      "country": "Bolivia"
    },
    "BAM": {
      "value": 1.95583,
      "currency": "Bosnia and Herzegovina convertible mark",
      "country": "Bosnia and Herzegovina"
    },
    "BWP": {
      "value": 15.49175,
      "currency": "Botswana pula",
      "country": "Botswana"
    },
    "BND": {
      "value": 1.45225,
      "currency": "Brunei dollar",
      "country": "Brunei"
    },
    "BIF": {
      "value": 3407.3895,
      "currency": "Burundi franc",
      "country": "Burundi"
    },
    "KHR": {
      "value": 4643,
      "currency": "Cambodian riel",
      "country": "Cambodia"
    },
    "CVE": {
      "value": 110.265,
      "currency": "Cape Verde escudo",
      "country": "Cape Verde"
    },
    "KYD": {
      "value": 0.94247,
      "currency": "Cayman Islands dollar",
      "country": "Cayman Islands"
    },
    "CLP": {
      "value": 1099.58414,
      "currency": "Chilean peso",
      "country": "Chile"
    },
    "COP": {
      "value": 3827.7705,
      "currency": "Colombian peso",
      "country": "Colombia"
    },
    "KMF": {
      "value": 492.615,
      "currency": "Comorian franc",
      "country": "Comoros"
    },
    "CDF": {
      "value": 2628.405,
      "currency": "Congolese franc",
      "country": "Congo (Democratic Republic of)"
    },
    "CRC": {
      "value": 517.35651,
      "currency": "Costa Rican colón",
      "country": "Costa Rica"
    },
    "CUP": {
      "value": 27.2904,
      "currency": "Cuban peso",
      "country": "Cuba"
    },
    "XCG": {
      "value": 2.03255,
      "currency": "Caribbean Guilder",
      "country": "Curaçao"
    },
    "DJF": {
      "value": 202.20416,
      "currency": "Djibouti franc",
      "country": "Djibouti"
    },
    "DOP": {
      "value": 67.6234,
      "currency": "Dominican peso",
      "country": "Dominican Republic"
    },
    "EGP": {
      "value": 59.24292,
      "currency": "Egyptian pound",
      "country": "Egypt"
    },
    "ERN": {
      "value": 17.11766,
      "currency": "Eritrean nakfa",
      "country": "Eritrea"
    },
    "SZL": {
      "value": 18.5887,
      "currency": "Swazi lilangeni",
      "country": "Eswatini"
    },
    "ETB": {
      "value": 184.034,
      "currency": "Ethiopian birr",
      "country": "Ethiopia"
    },
    "FKP": {
      "value": 0.85718,
      "currency": "Falkland Islands pound",
      "country": "Falkland Islands"
    },
    "FJD": {
      "value": 2.5441,
      "currency": "Fiji dollar",
      "country": "Fiji"
    },
    "GMD": {
      "value": 84.745,
      "currency": "Gambian dalasi",
      "country": "Gambia (the)"
    },
    "GEL": {
      "value": 2.9637,
      "currency": "Georgian lari",
      "country": "Georgia"
    },
    "GHS": {
      "value": 13.2472,
      "currency": "Ghana cedi",
      "country": "Ghana"
    },
    "GIP": {
      "value": 0.85718,
      "currency": "Gibraltar pound",
      "country": "Gibraltar"
    },
    "GTQ": {
      "value": 8.66954,
      "currency": "Guatemalan quetzal",
      "country": "Guatemala"
    },
    "GNF": {
      "value": 10000.795,
      "currency": "Guinean franc",
      "country": "Guinea"
    },
    "GYD": {
      "value": 237.925,
      "currency": "Guyana dollar",
      "country": "Guyana"
    },
    "HTG": {
      "value": 148.60856,
      "currency": "Haitian gourde",
      "country": "Haiti"
    },
    "HNL": {
      "value": 30.48233,
      "currency": "Honduran lempira",
      "country": "Honduras"
    },
    "IRR": {
      "value": 1560858.3,
      "currency": "Iranian rial",
      "country": "Iran"
    },
    "IQD": {
      "value": 1487.505,
      "currency": "Iraqi dinar",
      "country": "Iraq"
    },
    "JMD": {
      "value": 180.0144,
      "currency": "Jamaican dollar",
      "country": "Jamaica"
    },
    "JOD": {
      "value": 0.80507,
      "currency": "Jordanian dinar",
      "country": "Jordan"
    },
    "KZT": {
      "value": 501.655,
      "currency": "Kazakhstani tenge",
      "country": "Kazakhstan"
    },
    "KES": {
      "value": 147.54,
      "currency": "Kenyan shilling",
      "country": "Kenya"
    },
    "KWD": {
      "value": 0.34939,
      "currency": "Kuwaiti dinar",
      "country": "Kuwait"
    },
    "KGS": {
      "value": 99.32826,
      "currency": "Kyrgyzstani som",
      "country": "Kyrgyzstan"
    },
    "LAK": {
      "value": 25513.69,
      "currency": "Lao kip",
      "country": "Laos"
    },
    "LBP": {
      "value": 101684.025,
      "currency": "Lebanese pound",
      "country": "Lebanon"
    },
    "LSL": {
      "value": 18.5887,
      "currency": "Lesotho loti",
      "country": "Lesotho"
    },
    "LRD": {
      "value": 194.73825,
      "currency": "Liberian dollar",
      "country": "Liberia"
    },
    "LYD": {
      "value": 7.2708,
      "currency": "Libyan dinar",
      "country": "Libya"
    },
    "MOP": {
      "value": 9.18052,
      "currency": "Macanese pataca",
      "country": "Macau"
    },
    "MGA": {
      "value": 4989.5,
      "currency": "Malagasy ariary",
      "country": "Madagascar"
    },
    "MWK": {
      "value": 1971.74445,
      "currency": "Malawi kwacha",
      "country": "Malawi"
    },
    "MVR": {
      "value": 17.55483,
      "currency": "Maldivian rufiyaa",
      "country": "Maldives"
    },
    "MRU": {
      "value": 45.7229,
      "currency": "Mauritanian ouguiya",
      "country": "Mauritania"
    },
    "MUR": {
      "value": 53.975,
      "currency": "Mauritian rupee",
      "country": "Mauritius"
    },
    "MDL": {
      "value": 20.16,
      "currency": "Moldovan leu",
      "country": "Moldova"
    },
    "MNT": {
      "value": 4085.529,
      "currency": "Mongolian Tugrik",
      "country": "Mongolia"
    },
    "MAD": {
      "value": 10.97075,
      "currency": "Moroccan dirham",
      "country": "Morocco"
    },
    "MZN": {
      "value": 72.305,
      "currency": "Mozambique Metical",
      "country": "Mozambique"
    },
    "MMK": {
      "value": 4524.9675,
      "currency": "Myanmar Kyat",
      "country": "Myanmar"
    },
    "NAD": {
      "value": 18.5887,
      "currency": "Namibian dollar",
      "country": "Namibia"
    },
    "NPR": {
      "value": 174.63015,
      "currency": "Nepalese rupee",
      "country": "Nepal"
    },
    "XPF": {
      "value": 119.355,
      "currency": "CFP franc",
      "country": "New Caledonia"
    },
    "NIO": {
      "value": 41.7864,
      "currency": "Nicaraguan córdoba",
      "country": "Nicaragua"
    },
    "NGN": {
      "value": 1528.15,
      "currency": "Nigerian naira",
      "country": "Nigeria"
    },
    "MKD": {
      "value": 61.61,
      "currency": "Macedonian denar",
      "country": "North Macedonia"
    },
    "OMR": {
      "value": 0.43717,
      "currency": "Omani rial",
      "country": "Oman"
    },
    "PKR": {
      "value": 315.062,
      "currency": "Pakistan rupee",
      "country": "Pakistan"
    },
    "PAB": {
      "value": 1.1355,
      "currency": "Panamanian balboa",
      "country": "Panama"
    },
    "PGK": {
      "value": 5.0534,
      "currency": "Papua New Guinean kina",
      "country": "Papua New Guinea"
    },
    "PYG": {
      "value": 6669.35925,
      "currency": "Paraguayan guaraní",
      "country": "Paraguay"
    },
    "PEN": {
      "value": 3.90618,
      "currency": "Peruvian sol",
      "country": "Peru"
    },
    "QAR": {
      "value": 4.13322,
      "currency": "Qatari riyal",
      "country": "Qatar"
    },
    "RWF": {
      "value": 1675.645,
      "currency": "Rwandan franc",
      "country": "Rwanda"
    },
    "SHP": {
      "value": 0.85718,
      "currency": "Saint Helena pound",
      "country": "Saint Helena"
    },
    "WST": {
      "value": 3.13069,
      "currency": "Samoan tala",
      "country": "Samoa"
    },
    "STN": {
      "value": 24.5,
      "currency": "São Tomé and Príncipe dobra",
      "country": "Sao Tome and Príncipe"
    },
    "SAR": {
      "value": 4.26289,
      "currency": "Saudi riyal",
      "country": "Saudi Arabia"
    },
    "RSD": {
      "value": 117.375,
      "currency": "Serbian Dinar",
      "country": "Serbia (Republic of)"
    },
    "SCR": {
      "value": 15.90745,
      "currency": "Seychellois rupee",
      "country": "Seychelles"
    },
    "SLE": {
      "value": 27.6928,
      "currency": "Sierra Leonean leone",
      "country": "Sierra Leone"
    },
    "SBD": {
      "value": 9.1668,
      "currency": "Solomon Islands dollar",
      "country": "Solomon Islands"
    },
    "SOS": {
      "value": 649.855,
      "currency": "Somali shilling",
      "country": "Somalia"
    },
    "SSP": {
      "value": 6552.67879,
      "currency": "South Sudanese pound",
      "country": "South Sudan"
    },
    "LKR": {
      "value": 376.38,
      "currency": "Sri Lankan rupee",
      "country": "Sri Lanka"
    },
    "SDG": {
      "value": 5784.9421,
      "currency": "Sudanese Pound",
      "country": "Sudan"
    },
    "SRD": {
      "value": 42.82538,
      "currency": "Surinam dollar",
      "country": "Suriname"
    },
    "SYP": {
      "value": 139.4,
      "currency": "Syrian pound",
      "country": "Syria"
    },
    "TWD": {
      "value": 36.14615,
      "currency": "New Taiwan dollar",
      "country": "Taiwan"
    },
    "TJS": {
      "value": 10.47499,
      "currency": "Tajikistani somoni",
      "country": "Tajikistan"
    },
    "TZS": {
      "value": 2996.265,
      "currency": "Tanzanian shilling",
      "country": "Tanzania"
    },
    "TOP": {
      "value": 2.725,
      "currency": "Tongan paʻanga",
      "country": "Tonga"
    },
    "TTD": {
      "value": 7.71385,
      "currency": "Trinidad and Tobago dollar",
      "country": "Trinidad and Tobago"
    },
    "TND": {
      "value": 3.37965,
      "currency": "Tunisian dinar",
      "country": "Tunisia"
    },
    "TMT": {
      "value": 3.97425,
      "currency": "Turkmenistan manat",
      "country": "Turkmenistan"
    },
    "UGX": {
      "value": 4452,
      "currency": "Ugandan shilling",
      "country": "Uganda"
    },
    "UAH": {
      "value": 51.01115,
      "currency": "Ukrainian hryvnia",
      "country": "Ukraine"
    },
    "AED": {
      "value": 4.17655,
      "currency": "United Arab Emirates dirham",
      "country": "United Arab Emirates"
    },
    "UYU": {
      "value": 45.5222,
      "currency": "Uruguayan peso",
      "country": "Uruguay"
    },
    "UZS": {
      "value": 13406.81444,
      "currency": "Uzbekistan sum",
      "country": "Uzbekistan"
    },
    "VUV": {
      "value": 133.875,
      "currency": "Vanuatu vatu",
      "country": "Vanuatu"
    },
    "VES": {
      "value": 972.91371,
      "currency": "Venezuelan bolivar soberano",
      "country": "Venezuela"
    },
    "VND": {
      "value": 29494.04475,
      "currency": "Vietnamese dong",
      "country": "Vietnam"
    },
    "YER": {
      "value": 605.78925,
      "currency": "Yemeni rial",
      "country": "Yemen"
    },
    "ZMW": {
      "value": 22.2019,
      "currency": "Zambian Kwacha",
      "country": "Zambia"
    },
    "ZIG": {
      "value": 30.48954,
      "currency": "Zimbabwean gold",
      "country": "Zimbabwe"
    },
    "XCD": {
      "value": 3.07721,
      "currency": "East Caribbean dollar",
      "country": "Antigua and Barbuda"
    },
    "XOF": {
      "value": 655.957,
      "currency": "West African CFA franc",
      "country": "Benin"
    },
    "XAF": {
      "value": 655.957,
      "currency": "Central African CFA franc",
      "country": "Cameroon"
    }
  }
}
;
